server:
  port: 9527


#spring配置
spring:
  application:
    name: springcloud-zuul-geteway 
#eureka 的配置
eureka:
  client:
    service-url:
      # 服务注册到哪里 打开eureka服务配置以配置中的地址为准 
      # eureka配置好之后，开启eureka功能注解
      defaultZone: http://eureka7001.com:7001/eureka,http://eureka7001.com:7002/eureka,http://eureka7001.com:7003/eureka
  instance:
    # 修改eureka——Status up 描述
    instance-id: zuul9527.com
    prefer-ip-address: true
# actuator 监控配置
info:
  app.name: junjay.com
  company.name: blog.junjay.com
  # 服务开发者名称（作者）
  author: junjay
  
# zuul 配置
zuul:
  ignored-services: springcloud-provider-dept #不能再使用本服务路径访问，ignored忽略  routes:
    # 原来要用springcloud-provider-dept 现在可以使用/mydept 代替微服务名称
    provider:
      path: /mydept/**
      url: springcloud-provider-dept   
  